---
- name: Install Postgres
  hosts: postgres
  roles:
  - name: postgres-install
    become: yes
  - name: postgres-config
    become: yes

- name: Install Redmine
  hosts: redmine_servers
  roles:
  - name: redmine-install
    become: yes
  - name: redmine-config
    become: yes
    become_user: "{{ redmine_user }}"
  - name: redmine-plugins
    become: yes
    become_user: "{{ redmine_user }}"

- name: Install nginx
  hosts: redmine_servers
  roles:
  - name: nginx-install
    become: yes
  # - name: nginx-config
  #   become: yes
  - name: nginx-redmine
    become: yes
