---
# defaults file for redmine-config
redmine_db_adaptor: postgresql
redmine_db_host: localhost
redmine_db_port: 5432 
redmine_db_name: redmine
redmine_db_username: redmine
redmine_db_password: password
redmine_db_encoding: utf8
redmine_db_num_pool: 5

mail_smtp_host: localhost
mail_smtp_port: 25
mail_domain: localhost

redmine_dir: /srv/redmine

redmine_user: redmine
redmine_group: redmine
