---
# defaults file for redmine-config
db_adaptor: postgresql
db_host: localhost
db_port: 5432 
db_name: redmine
db_username: redmine
db_password: password
db_encoding: utf8
db_num_pool: 5

mail_smtp_host: localhost
mail_smtp_port: 25
mail_domain: localhost
