- name: Add group - {{ redmine_group }}
  group:
    name: "{{ redmine_group }}"

- name: Add user - {{ redmine_user }}
  user:
      name: "{{ redmine_user }}"
      group: "{{ redmine_group }}"
      home: "{{ redmine_dir }}"
      create_home: yes

- name: make redmine directory
  file:
    path: "{{ redmine_dir }}"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    state: directory
    mode: '0755'

- name: download package
  get_url:
    dest: "{{ redmine_dir }}/{{ redmine_package_name }}"
    url: "{{ redmine_package_url }}"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    checksum: "md5:{{ redmine_package_url }}.md5"
    mode: '0644'

- name: Unpack redmine archive
  unarchive:
    src: "{{ redmine_dir }}/{{ redmine_package_name }}"
    remote_src: yes
    dest: "{{ redmine_dir }}"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    creates: "{{ redmine_dir }}/CONTRIBUTING.md"
    extra_opts:
    - '--strip-components=1'

- name: chcon
  file:
    path: "{{ redmine_dir }}/bin/bundle"
    setype: bin_t

- name: Install Epel
  dnf:
    name: epel-release

- name: Install packages
  dnf:
    name:
    - ruby
    - rubygem-bundler
    - "@Development Tools"
    - ruby-devel
    - zlib-devel
    - libpq-devel
    - ImageMagick
    - ImageMagick-devel
    enablerepo: PowerTools

- name: Install redmined
  include: redmined.yml
