- name: Add group - {{ redmine_group }}
  group:
    name: "{{ redmine_group }}"

- name: Add user - {{ redmine_user }}
  user:
      name: "{{ redmine_user }}"
      group: "{{ redmine_group }}"
      home: "{{ redmine_dir }}"
      create_home: yes

- name: make redmine directory
  file:
    path: "{{ redmine_dir }}"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    state: directory
    mode: '0755'

- name: make redmine log directory
  file:
    path: "{{ redmine_log_dir }}"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    state: directory
    mode: '0755'

- name: link redmine log directory
  file:
    src: "{{ redmine_log_dir }}"
    dest: "{{ redmine_dir }}/log"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    state: link

- name: download package
  get_url:
    dest: "{{ redmine_dir }}/{{ redmine_package_name }}"
    url: "{{ redmine_package_url }}"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    checksum: "md5:{{ redmine_package_url }}.md5"
    mode: '0644'

- name: Unpack redmine archive
  unarchive:
    src: "{{ redmine_dir }}/{{ redmine_package_name }}"
    remote_src: yes
    dest: "{{ redmine_dir }}"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    creates: "{{ redmine_dir }}/CONTRIBUTING.md"
    extra_opts:
    - '--strip-components=1'

- name: add additionnal_environment.rb
  template:
    src: additional_environment.rb
    dest: "{{ redmine_dir }}/config/additional_environment.rb"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    mode: '0644'

- name: chcon
  file:
    path: "{{ redmine_dir }}/bin/bundle"
    setype: bin_t

- name: Install Epel
  dnf:
    name: epel-release
  register: task_install_epel
  failed_when: task_install_epel.rc not in [0, 1]

- name: Install epel 2 - install gpg key
  rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
  when: task_install_epel.rc == 1

- name: Install epel 2 - install epel.rpm
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: installed
  when: task_install_epel.rc == 1

- name: Install packages
  dnf:
    name:
    - ruby
    - rubygem-bundler
    - "@Development Tools"
    - ruby-devel
    - zlib-devel
    - libpq-devel
    - ImageMagick
    - ImageMagick-devel
    - subversion
    - git
    enablerepo: PowerTools,codeready-builder-for-rhel-8-rhui-rpms

- name: Install redmined
  include: redmined.yml

- name: patch for svn
  patch:
    src: subversion_adapter.rb.patch
    dest: "{{ redmine_dir }}lib/redmine/scm/adapters/subversion_adapter.rb"
    remote_src: no

- name: add logrotate config
  template:
    src: redmine.logrotate.conf
    dest: /etc/logrotate.d/redmine
    mode: '0644'
