---
# tasks file for redmine-config
- name: database.ymlの作成
  template:
    src: database.yml
    dest: "{{ redmine_dir }}/config/database.yml"
  register:
    result_database_yml

- name: configuration.ymlの作成
  template:
    src: configuration.yml
    dest: "{{ redmine_dir }}/config/configuration.yml"

- name: Additoinal gem pakcages
  copy:
    src: Gemfile.local
    dest: "{{ redmine_dir }}/Gemfile.local"

- name: Install gem packages
  bundler:
    executable: "{{ redmine_dir }}/bin/bundle"
    chdir: "{{ redmine_dir }}"
    state: present
    clean: no
    user_install: yes
    extra_args: "--path vendor/bundle"

- name: Update gem packages
  bundler:
    executable: "{{ redmine_dir }}/bin/bundle"
    chdir: "{{ redmine_dir }}"
    state: latest

- name: secret tokenの作成
  command:
    bundle exec rake generate_secret_token
  args:
    chdir: "{{ redmine_dir }}"
    creates: "{{ redmine_dir }}/config/initializers/secret_token.rb"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: データベースのマイグレーション
  command:
    bundle exec rake db:migrate
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: デフォルトデータ(日本語)をロード
  command:
    bundle exec rake redmine:load_default_data
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
    REDMINE_LANG: ja
  when: result_database_yml is changed

- name: デフォルトの言語を日本語に変更
  command:
    bundle exec rails r 'Setting["default_language"]="ja"'
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: ユーザー名の表示形式を「姓 名」に変更
  command:
    bundle exec rails r 'Setting["user_format"]=:lastname_firstname'
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: 添付ファイルとリポジトリのエンコーディングを設定
  command:
    bundle exec rails r 'Setting["repositories_encodings"]="UTF-8,CP932,EUC-JP"'
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: 添付ファイルのサムネイルを表示
  command:
    bundle exec rails r 'Setting["thumbnails_enabled"]="1"'
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
