---
# tasks file for nginx-install
- name: Install package
  dnf:
    name:
    - nginx

- name:
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: enable service
  systemd:
    name: nginx
    enabled: yes
  notify: restart nginx

- name: "open firewall - http, https"
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
  - http
  - https
  notify: restart firewalld
  when: ansible_system_vendor != "Amazon EC2"

- name: add logrotate config
  template:
    src: nginx.logrotate.conf
    dest: /etc/logrotate.d/nginx
    mode: '0644'

- name: chmod log dir
  file:
    path: "{{ nginx_log_dir }}"
    mode: '0755'
