---
# redmine_backlogs
- name: Checkout redmine_backlogs
  git:
    repo: "{{ redmine_backlog_plugin_repo_url }}"
    dest: "{{ redmine_plugin_dir }}/redmine_backlogs"
    version: "{{ redmine_backlog_plugin_branch }}"
  notify: redmine migration plugins

- name: patch app/query.rb
  patch:
    src: query.rb.patch
    dest: "{{ redmine_dir }}/app/models/query.rb"
    remote_src: no
  notify: redmine migration plugins

- name: Initial Setup redmine_backlogs
  copy:
    src: "{{ redmine_plugin_dir }}/redmine_backlogs/lib/labels/labels.yaml.default"
    dest: "{{ redmine_plugin_dir }}/redmine_backlogs/lib/labels/labels.yaml"
    remote_src: yes
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    mode: '0644'
  notify: redmine migration plugins
